// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('RegistroServicioError', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('RegistroServicioError', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1024, 852)
    await driver.findElement(By.css(".menu-navbar > button")).click()
    await driver.findElement(By.xpath("//input[@id=\'input-with-icon-textfield\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'input-with-icon-textfield\']")).sendKeys("VuelosExpress")
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[2]")).click()
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[2]")).sendKeys("vuelo@gmailcom")
    await driver.findElement(By.css(".MuiBox-root:nth-child(7)")).click()
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[3]")).click()
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[3]")).sendKeys("contra123")
    await driver.findElement(By.css(".Mui-focused > #input-with-icon-textfield")).click()
    {
      const element = await driver.findElement(By.xpath("(//button[@type=\'button\'])[2]"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[4]")).sendKeys("contra123")
    await driver.findElement(By.xpath("(//button[@type=\'button\'])[2]")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
