// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ReservarAutoCorrecto', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ReservarAutoCorrecto', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1024, 852)
    await driver.findElement(By.xpath("//div[11]/a/img")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[4]/div/div[2]/button")).click()
  })
})
