// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ReservarAutoError', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ReservarAutoError', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1024, 852)
    await driver.findElement(By.css(".MuiPaper-root:nth-child(14) .MuiCardMedia-root")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.xpath("//input[@id=\'meeting-time\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'meeting-time\']")).sendKeys("2022-07-05T20:03")
    await driver.findElement(By.css(".btn-primario")).click()
  })
})
