// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('AgregarVueloError', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('AgregarVueloError', async function() {
    await driver.get("http://localhost:3000/misServiciosAerolinea")
    await driver.manage().window().setRect(1024, 852)
    {
      const element = await driver.findElement(By.css(".btn-primario"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.xpath("(//button[@type=\'button\'])[3]")).click()
    await driver.findElement(By.xpath("//input[@id=\'input-with-icon-textfield\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'input-with-icon-textfield\']")).sendKeys("1500")
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[2]")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-root:nth-child(13)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".Mui-focused > #input-with-icon-textfield")).sendKeys("25")
    await driver.findElement(By.css(".MuiButton-root:nth-child(13)")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
