// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('AgregarVueloCorrecto', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('AgregarVueloCorrecto', async function() {
    await driver.get("http://localhost:3000/misServiciosAerolinea")
    await driver.manage().window().setRect(1024, 852)
    {
      const element = await driver.findElement(By.xpath("(//button[@type=\'button\'])[3]"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.xpath("(//button[@type=\'button\'])[3]")).click()
    await driver.findElement(By.xpath("//input[@id=\'input-with-icon-textfield\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'input-with-icon-textfield\']")).sendKeys("2500")
    await driver.findElement(By.xpath("//input[@id=\'meeting-time\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'meeting-time\']")).sendKeys("2022-07-05T19:09")
    {
      const element = await driver.findElement(By.xpath("//form[3]/div/div/div"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.xpath("//body/div[3]/div"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.xpath("//li[contains(.,\'San Cristobal, Guatemala\')]")).click()
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[2]")).click()
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[2]")).sendKeys("150")
    await driver.findElement(By.name("file")).click()
    await driver.findElement(By.name("file")).sendKeys("C:\\fakepath\\vuelo1.jpg")
    {
      const element = await driver.findElement(By.css(".MuiButton-root:nth-child(13)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-root:nth-child(13)")).click()
  })
})
