// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('RegistroTuristaError', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('RegistroTuristaError', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1024, 852)
    await driver.findElement(By.css(".MuiButton-sizeMedium")).click()
    await driver.findElement(By.xpath("//input[@id=\'input-with-icon-textfield\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'input-with-icon-textfield\']")).sendKeys("Benito")
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[2]")).click()
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[2]")).sendKeys("Martinez")
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[3]")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/div/div[2]/form[4]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/div/div[2]/form[4]/div/div/input")).sendKeys("1994-03-08T13:21")
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[4]")).click()
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[4]")).sendKeys("Contra231")
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[5]")).click()
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[5]")).sendKeys("Contra231")
    await driver.findElement(By.css(".MuiBox-root:nth-child(9) > .btn-primario")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
  })
})
