// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ReservarHabitacionCorrecto', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ReservarHabitacionCorrecto', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1024, 852)
    {
      const element = await driver.findElement(By.css("div:nth-child(3) > .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("div:nth-child(2) > .MuiIconButton-root path")).click()
    await driver.findElement(By.css(".MuiPaper-root:nth-child(4) .MuiCardMedia-root")).click()
    await driver.findElement(By.css(".btn-primario")).click()
  })
})
