// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('errorAsginarClase', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('errorAsginarClase', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1920, 1053)
    await driver.findElement(By.xpath("//input[@id=\'CorreoEst\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'CorreoEst\']")).sendKeys("stacy_gwen@gmail.com")
    await driver.findElement(By.xpath("//input[@id=\'ContraEst\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'ContraEst\']")).sendKeys("134625")
    await driver.findElement(By.css(".MuiBox-root:nth-child(3) > .MuiButton-root")).click()
    await driver.findElement(By.css(".MuiBox-root:nth-child(2) > .MuiButton-root")).click()
    await driver.findElement(By.xpath("//input[@id=\'Nombre\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'Nombre\']")).sendKeys("Gwen Stacy")
    await driver.findElement(By.xpath("//input[@id=\'Curso\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'Curso\']")).sendKeys("Ingles")
    await driver.findElement(By.xpath("//input[@id=\'Seccion\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'Seccion\']")).sendKeys("A")
    await driver.findElement(By.xpath("//input[@id=\'Dia\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'Dia\']")).sendKeys("Jueves")
    await driver.findElement(By.xpath("//input[@id=\'Hora\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'Hora\']")).sendKeys("11:00")
    await driver.findElement(By.css(".MuiBox-root:nth-child(2) > .MuiButton-root")).click()
  })
})
