// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('inciarSesionEstudiante', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('inciarSesionEstudiante', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1920, 1053)
    await driver.findElement(By.xpath("//input[@id=\'CorreoEst\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'CorreoEst\']")).sendKeys("theamazingspiderman@gmail.com")
    await driver.findElement(By.xpath("//input[@id=\'ContraEst\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'ContraEst\']")).sendKeys("282828")
    await driver.findElement(By.css(".MuiBox-root:nth-child(3) > .MuiButton-root")).click()
    await driver.findElement(By.css(".MuiTypography-h5")).click()
    await driver.findElement(By.css(".MuiTypography-body2")).click()
  })
})
