// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ReservarVueloCorrecto', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ReservarVueloCorrecto', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1024, 852)
    {
      const element = await driver.findElement(By.css("div:nth-child(3) > .MuiIconButton-sizeLarge > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("div:nth-child(3) > .MuiIconButton-sizeLarge > .MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiPaper-root:nth-child(8) .MuiCardMedia-root")).click()
    await driver.findElement(By.id("meeting-time")).click()
    await driver.findElement(By.id("meeting-time")).sendKeys("2022-07-19T19:30")
    await driver.findElement(By.css(".Mui-focused > #meeting-time")).click()
    await driver.findElement(By.css(".Mui-focused > #meeting-time")).sendKeys("2022-07-28T19:30")
    await driver.findElement(By.id("outlined-number")).sendKeys("2")
    await driver.findElement(By.id("outlined-number")).click()
    await driver.findElement(By.css(".btn-primario")).click()
  })
})
