// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('AgregarHabitacionCorrecto', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('AgregarHabitacionCorrecto', async function() {
    await driver.get("http://localhost:3000/misServiciosHotel")
    await driver.manage().window().setRect(1024, 852)
    {
      const element = await driver.findElement(By.css(".btn-primario"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".btn-primario")).click()
    await driver.findElement(By.xpath("//input[@id=\'input-with-icon-textfield\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'input-with-icon-textfield\']")).sendKeys("350")
    await driver.findElement(By.xpath("//input[@id=\'meeting-time\']")).click()
    await driver.findElement(By.xpath("//input[@id=\'meeting-time\']")).sendKeys("2022-07-05T18:32")
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[2]")).click()
    await driver.findElement(By.xpath("(//input[@id=\'input-with-icon-textfield\'])[2]")).sendKeys("3")
    await driver.findElement(By.name("file")).click()
    await driver.findElement(By.name("file")).sendKeys("C:\\fakepath\\habitacion4.jpg")
    await driver.findElement(By.css(".MuiButton-root:nth-child(11)")).click()
  })
})
